# Generated by Django 6.0.3 on 2026-03-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(help_text='Identificador único interno ou código de barras.', max_length=50, verbose_name='Código (SKU)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='excluido',
            field=models.BooleanField(default=False, verbose_name='Produto Excluído'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(help_text='Nome comercial que será exibido aos clientes.', max_length=100, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor',
            field=models.DecimalField(decimal_places=2, help_text='Preço de venda atual do produto.', max_digits=10, verbose_name='Valor Unitário'),
        ),
        migrations.AlterModelTable(
            name='produto',
            table='tb_produtos',
        ),
    ]
